channels:
- conda-forge
dependencies:
- python=3.12
- pip
- astra-toolbox
- hyperopt
- xdesign
- pip:
  - colour_demosaicing
  - ray[tune]
  - bm3d
  - jaxlib>=0.4.26
  - jax>=0.4.26
  - git+https://github.com/lanl/scico
